<?php

declare(strict_types=1);

namespace App\Modules\Orders\Models;

use App\Modules\Customers\Models\Customer;
use Database\Factories\OrderFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;

/**
 * A mirror of a Woo order — Woo stays the source of truth. Money is int Toman.
 * `status` is the raw Woo slug; whether it counts as realized comes from
 * config('woo.realized_statuses'), never from a string in code.
 *
 * @property int $id
 * @property int $woo_order_id
 * @property int $customer_id
 * @property string|null $number
 * @property string $status
 * @property bool $is_realized
 * @property int $total
 * @property int $subtotal
 * @property int $discount_total
 * @property int $shipping_total
 * @property int $tax_total
 * @property int $refunded_total
 * @property-read int $net_revenue generated by PostgreSQL: total - refunded_total
 * @property bool $is_fully_refunded
 * @property list<string> $coupon_codes
 * @property string|null $payment_method
 * @property Carbon $ordered_at
 * @property Carbon|null $paid_at
 * @property Carbon|null $completed_at
 * @property Carbon|null $woo_modified_at
 * @property Carbon $synced_at
 */
class Order extends Model
{
    /** @use HasFactory<OrderFactory> */
    use HasFactory, SoftDeletes;

    /** net_revenue is deliberately absent: it is a database-generated column. */
    protected $fillable = [
        'woo_order_id', 'customer_id', 'number', 'status', 'is_realized',
        'total', 'subtotal', 'discount_total', 'shipping_total', 'tax_total', 'refunded_total',
        'is_fully_refunded', 'coupon_codes', 'payment_method',
        'ordered_at', 'paid_at', 'completed_at', 'woo_modified_at', 'synced_at',
    ];

    protected function casts(): array
    {
        return [
            'is_realized' => 'boolean',
            'is_fully_refunded' => 'boolean',
            'total' => 'integer',
            'subtotal' => 'integer',
            'discount_total' => 'integer',
            'shipping_total' => 'integer',
            'tax_total' => 'integer',
            'refunded_total' => 'integer',
            'net_revenue' => 'integer',
            'coupon_codes' => 'array',
            'ordered_at' => 'datetime',
            'paid_at' => 'datetime',
            'completed_at' => 'datetime',
            'woo_modified_at' => 'datetime',
            'synced_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<Customer, $this> */
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    /** @return HasMany<OrderItem, $this> */
    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class);
    }

    /** @return HasMany<OrderStatusHistory, $this> */
    public function statusHistory(): HasMany
    {
        return $this->hasMany(OrderStatusHistory::class);
    }

    /** @return HasMany<Refund, $this> */
    public function refunds(): HasMany
    {
        return $this->hasMany(Refund::class);
    }

    protected static function newFactory(): OrderFactory
    {
        return OrderFactory::new();
    }
}
